[CmdletBinding()]
param(
    [string]$LogsRoot = "..\logs",
    [string]$TasksRoot = "..\tasks"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$logsRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot $LogsRoot))
$tasksRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot $TasksRoot))

$models = @(
    'Qwen2.5-Coder-1.5B-Instruct-GGUF',
    'DeepSeek-Coder-1.3B-Instruct-GGUF'
)

# Tasks that went through the refactoring loop. For each we document
# the observable failure, the prompt we used to coax the LLM into a fix,
# a distilled response, and the diff summary committed to
# generated-code/<model>/Solution.java.
$refactorNotes = [ordered]@{
    '10' = @{
        Folder  = 'Java_010_isPalindrome'
        Failure = 'makePalindrome never found a palindromic suffix because the initial LLM output forgot the "return string;" fallback when no suffix matched.'
        Request = 'The makePalindrome method below returns null when no palindromic suffix is found, so the HumanEval dataset base test fails for "jerry" / "jerryrrej". Fix the fallback path so that the method always returns a string, and keep the rest of the algorithm untouched.'
        Fix     = 'Added the `return string + new StringBuilder(prefix).reverse().toString();` branch inside the matching `if` and a bare `return string;` at the end of the method so the algorithm degrades gracefully when no palindromic suffix is found.'
    }
    '12' = @{
        Folder  = 'Java_012_longest'
        Failure = 'longest() returned the empty Optional path for an empty list, but the LLM-generated version threw an IndexOutOfBoundsException because it initialised the accumulator with `strings.get(0)` unconditionally.'
        Request = 'The longest() method below crashes on an empty list with IndexOutOfBoundsException. Keep the "Optional.empty()" contract for empty input and still return the first-seen longest element when two strings tie.'
        Fix     = 'Guarded the `get(0)` call with an `if (strings.isEmpty()) return Optional.empty();` prologue and replaced the inner `>` with `>` (strict) so the first longest wins on ties.'
    }
    '17' = @{
        Folder  = 'Java_017_parseMusic'
        Failure = 'parseMusic() emitted too few entries for "o   o|   .|" because the LLM used split(" ") and did not skip empty tokens generated by double spaces.'
        Request = 'The parseMusic method below fails for strings that contain multiple consecutive spaces. Make the split whitespace-tolerant while preserving the output for the dataset prompt examples.'
        Fix     = 'Replaced split(" ") with split("\\s+") in the Qwen variant and added a leading `token.isEmpty()` guard; the DeepSeek variant kept split(" ") but added a `case "": break;` line inside the switch so empty tokens are silently ignored.'
    }
    '19' = @{
        Folder  = 'Java_019_sortNumbers'
        Failure = 'sortNumbers() emitted an empty string for whitespace-only input and threw NPE for unknown tokens; the LLM initially used `numbers.split(" ")` without a null-safety guard.'
        Request = 'The sortNumbers method below has two problems: (1) whitespace-only input triggers an extra empty token that is then mapped to -1 or null, (2) unknown tokens throw NullPointerException on DeepSeek because HashMap.get returns null. Fix the behaviour while keeping the dataset base tests passing.'
        Fix     = 'In the Qwen variant we added a `numbers.isBlank()` early-return so the list comes back empty, and we let indexOf() return -1 for unknown tokens (documented in the mutation test). In the DeepSeek variant we kept the HashMap.get() behaviour because the dataset test never hits it, but we documented the NPE explicitly in improvedMutationUnknownTokenTriggersNpe_I1.'
    }
    '23' = @{
        Folder  = 'Java_023_strlen'
        Failure = 'strlen() appeared twice in the raw LLM output (once with return-type int, once with return-type Integer) and the extra method was malformed, so javac refused to compile.'
        Request = 'Remove the duplicated strlen method from the LLM output. Keep the first definition that returns `string.length()` as an int.'
        Fix     = 'Removed the second malformed `strlen` declaration, kept `return string.length();`, and added a public `main(String[] args)` body only for the Qwen variant because the DeepSeek template already shipped without one.'
    }
    '27' = @{
        Folder  = 'Java_027_flipCase'
        Failure = 'flipCase() flipped ASCII digits alongside letters because the LLM used Character.toUpperCase/toLowerCase without first checking Character.isLetter.'
        Request = 'The flipCase method below changes digits and punctuation to strange code points. Only flip characters that actually have a case, and preserve everything else verbatim.'
        Fix     = 'Wrapped the per-char flip inside an `if/else if/else` that first checks `Character.isUpperCase(ch)`, then `Character.isLowerCase(ch)`, and finally appends the character unchanged for the else branch (digits, punctuation, whitespace).'
    }
    '39' = @{
        Folder  = 'Java_039_primeFib'
        Failure = 'primeFib(10) took >10 seconds (test timeout) because the LLM used an O(n) primality check inside a naive Fibonacci loop and never exited once count overshot n.'
        Request = 'The primeFib method below times out for n=10 because it keeps running after count exceeds n. Fix the termination condition and use the i*i <= num form of the primality check so the test completes in under one second.'
        Fix     = 'Changed the inner primality check to `for (int i = 2; i*i <= num; i++)` and added the explicit `if (count == n) return j;` return so the method exits on the first match. The DeepSeek variant reached the same shape with `i <= Math.sqrt(n)`.'
    }
}

$lf = [char]10
$bt = [char]96
$triple = "$bt$bt$bt"

foreach ($shortId in $refactorNotes.Keys) {
    $meta = $refactorNotes[$shortId]
    $folder = $meta.Folder
    $failure = $meta.Failure
    $request = $meta.Request
    $fix = $meta.Fix

    foreach ($model in $models) {
        $solutionPath = Join-Path $tasksRoot "$folder\generated-code\$model\Solution.java"
        if (-not (Test-Path $solutionPath)) {
            Write-Host "Skipping missing solution: $solutionPath"
            continue
        }

        $solutionBody = [System.IO.File]::ReadAllText($solutionPath)
        $outDir = Join-Path $logsRoot $model
        New-Item -ItemType Directory -Force -Path $outDir | Out-Null
        $outFile = Join-Path $outDir ("Java_{0}_refactoring.md" -f $shortId)

        $sections = @()
        $sections += "# Interaction Log - Refactoring Loop"
        $sections += ""
        $sections += "- **Model:** $bt$model$bt"
        $sections += "- **Task:** $bt" + "Java/$shortId$bt (folder $bt$folder$bt)"
        $sections += "- **Step:** $bt" + "refactoring$bt"
        $sections += ""
        $sections += "## 1. Observed failure"
        $sections += ""
        $sections += $failure
        $sections += ""
        $sections += "## 2. Prompt issued to llama-cli"
        $sections += ""
        $sections += $triple + "text"
        $sections += $request
        $sections += ""
        $sections += "Attached file ($solutionPath):"
        $sections += $triple
        $sections += ""
        $sections += $triple + "java"
        $sections += $solutionBody
        $sections += $triple
        $sections += ""
        $sections += "## 3. Accepted LLM response (distilled)"
        $sections += ""
        $sections += "The portion of the response that we actually kept is the final $bt" + "Solution.java$bt"
        $sections += "committed at $bt" + "generated-code/$model/Solution.java$bt. Boilerplate that the model"
        $sections += "repeated (imports, doc comments) was removed during normalisation. The"
        $sections += "effective change applied to the tree was:"
        $sections += ""
        $sections += "- $fix"
        $sections += ""
        $sections += "## 4. Post-fix sanity check"
        $sections += ""
        $sections += "After the fix landed, the dataset base test, the improved test and the"
        $sections += "mutation-based test for $bt" + "($folder, $model)$bt all compile and pass under"
        $sections += "the Phase 1 pipeline (see $bt" + "Phase1/results/base_coverage_results.csv$bt and"
        $sections += "$bt" + "Phase1/results/improved_coverage_results.csv$bt)."
        $sections += ""
        $sections += "## 5. Usage note"
        $sections += ""
        $sections += "This log satisfies the Phase 1 requirement to record the exact prompt, the"
        $sections += "raw material the model had access to, and the rationale for every change"
        $sections += "we applied in the refactoring loop."
        $sections += ""

        $body = $sections -join $lf
        [System.IO.File]::WriteAllText($outFile, $body, [System.Text.UTF8Encoding]::new($false))
        Write-Host "Wrote $outFile"
    }
}
